{
 "title": "Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PM2.5",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pm25" }
   ]
  },
  {
   "title": "PM10",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    { "expr": "pm10" }
   ]
  },
  {
   "title": "TVOC",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "targets": [
    { "expr": "tvoc" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "Time Series",
   "type": "graph",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pm25", "legendFormat": "PM2.5" },
    { "expr": "pm10", "legendFormat": "PM10" },
    { "expr": "tvoc", "legendFormat": "TVOC" },
    { "expr": "humidity", "legendFormat": "Humidity" },
    { "expr": "temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 8 },
   "targets": [
    { "expr": "temperature" }
   ]
  }
 ]
}